### ISSUE TITLE
Find a conda-only solution for eidl

### ISSUE THREAD

**Issue by haasad** [haasad/EcoInventDownLoader#3]
Currently a manual installation of `7zip` is required to use `eidl`. It would be way more convenient to have an 7z-capable unarchive program installed via conda. This would also make it possible to include `eidl` as a dependency to `bw2io` to use `eidl` directly via `brightway`.

Options:
- __libarchive__:
    - since around two months `libarchive` is available for all three major OS on the official anaconda channel (windows was missing before)
   - the only python wrapper for `libarchive` that I could get to work is [python-libarchive-c](https://github.com/Changaco/python-libarchive-c)
   - `libarchive-c` works fine on linux, but fails to extract a 7z archive on windows, I get the error message described [here](https://github.com/Changaco/python-libarchive-c/issues/66)
- __7zip conda package__:
    - while there is no conda channel that provides 7zip/p7zip for all OSs, there appears to be at least [one example for every OS](https://anaconda.org/search?q=7zip)
   - would need to package these myself and test on all OS, otherwise the channel requirements for brightway get out of hand

ping @cmutel, picking up from our email conversation from some weeks ago

**Comment by cmutel** [comment]
I have also been looking at this, and have played around a bit with libarchive, but without any progress. Unfortunately, 7zip seems to compress ecoinvent particularly well - I tried different compression levels with zip, bz2, and gz. I don't have the exact numbers, but think that 7zip for 3.4 cutoff is around 70 MB, and the best alternative, bz2 was around 110 MB. Still might be worth asking if ecoinvent would post `.tar.bz2`, this would allow the use of the standard lib.

Maybe you already do this, but I would save the compressed archive in a system directory (using `appdirs`) to avoid downloading more than once.

**Comment by haasad** [comment]
I created https://github.com/haasad/eidl7zip to solve this issue. I provides a command-line version of the 7zip program for all three OSs. I'll make a PR for `bw2io` when I find the time, @cmutel.
