### ISSUE TITLE
Ecoquery support for direct access flow will be removed

### ISSUE THREAD

**Issue by cmutel** [haasad/EcoInventDownLoader#33]
See https://github.com/brightway-lca/ecoinvent_interface/issues/34 and resolution in https://github.com/brightway-lca/ecoinvent_interface/pull/37. Timeline for turning off existing functionality is in February 2025.

**Comment by haasad** [comment]
Thank you very much for the notification. Since the activity-browser is anyway not using this project anymore I'll archive it.
